kuka_kr60:
  kuka_kr60_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6

    gains:
      joint_a1: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_a2: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_a3: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_a4: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_a5: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_a6: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}


